### ISSUE TITLE
Discussion about WeekView wrapped by SafeArea

### ISSUE THREAD

**Issue by porum** [SimformSolutionsPvtLtd/flutter_calendar_view#146]
This library is great, but I have a little problem about WeekView. In my case, out app is landscape and fullscreen without statusbar, but weekview cannot expand to status bar.
So, whether to consider remove SafeArea.
![IMG_20221130_150645](https://user-images.githubusercontent.com/48167317/204735227-a3eb8ec4-dbc1-486d-ac0b-bb7d382fe875.jpg)

**Comment by porum** [comment]
DayView also have the same problem.
![Screenshot_2022-12-01-16-41-40-529_com calendar page example example](https://user-images.githubusercontent.com/48167317/205007027-1e5bdf0d-4294-4efb-adf0-b50c3125402c.jpg)

**Comment by PRBaraiya** [comment]
Thanks for pointing this out @porum. We have planned this and decided to add a bool flag to define whether safe area should be added or not. Default value of this flag will be true. because we don't want current users to face issues. We will make these changes in short time. Or you are welcome to do it as well if you want.

**Comment by porum** [comment]
Hi @PRBaraiya, I have commit a pr to fix this bug.
