### ISSUE TITLE
Different types of variables at the same function

### ISSUE THREAD

**Issue by Saliim17** [SimformSolutionsPvtLtd/flutter_calendar_view#182]
The function weekDayBuilder has different type of variable according to the view calendar. If its weekview, the function has date as a DateTime but if we use MonthView is an integer. Why? 

WEEKVIEW:

![Captura de pantalla 2023-02-04 123951](https://user-images.githubusercontent.com/71647682/216765281-374e6630-44d2-4d84-a1e3-6f792fd8a34b.png)

MONTHVIEW:

![Captura de pantalla 2023-02-04 123931](https://user-images.githubusercontent.com/71647682/216765267-c20f3b30-1a02-49ea-910b-14f6ddfbcd8f.png)

**Comment by Saliim17** [comment]
Also different variables in oneventap of month and day view: 

MONTH VIEW: 
![image (1)](https://user-images.githubusercontent.com/71647682/216770621-61fcbfc0-5126-45da-98bb-8985f7d3d069.png)

WEEK VIEW: 
![image (2)](https://user-images.githubusercontent.com/71647682/216770623-12e67ed0-6779-4dd2-a846-eaf9f2c2031c.png)

**Comment by ParthBaraiya** [comment]
@Saliim17  Closing this as there is no problem with development.

 In `MonthView` `weekDayBuilder` accepts `int` (which represents the number of day in week) because that's what we need to show the week title. But in `WeekView`, we need date as well that's why `weekDayBuilder` in week view accepts `DateTime` instead of `int`.

Same for `onEventTap`. `onEventTap` is called when user taps on any event tile. In monthview evey event tile will have only one event. But in `WeekView` and `DayView` when `MergeEventArranger` is used, event tile can have multiple events.


If you have any better suggestions on how these functions should be implemented, feel free to reopen this issue and share it with us.
