### ISSUE TITLE
[ How to customize days' labels, am/pm stuff and the date selector widget ? ]

### ISSUE THREAD

**Issue by Gobmichet** [SimformSolutionsPvtLtd/flutter_calendar_view#212]
Hi,
Thanks for the job.
My question is about the customization about the day/week/month views.
Indeed, i'd like to cutomize those things :
- days' labels (I'd want the french days or abreviations)
-  am/pm stuff (would like to have time on  24 hours)
- date selector widget at the top of each view, color and selected date format

I saw the majority of customization is in the DayView<Event>() widget for the day view but i don't see how to customize the things i listed above ?

Thanks in advance.
Regards,

**Comment by faiyaz-shaikh** [comment]
Hi @Gobmichet you can check out class parameters according to your requirements. 
https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/blob/master/lib/src/day_view/day_view.dart#:~:text=class%20DayView%3CT%20extends%20Object%3F%3E%20extends%20StatefulWidget%20%7B

**Comment by Gobmichet** [comment]
Hi, 
Thanks for your answer, i did found what to do for all the listed above in the meanwhile ^^

However, there's just one more  thing i couldn't achieve::

> for the daxyView, i'd like to show just between 8AM and 6PM... is it possible ?
> if not, could i center the day view in order that 12 oclock is i the middle of the screen ?

Thanks in advance,
regards.

**Comment by muneebahmad0600** [comment]
> Hi, Thanks for your answer, i did found what to do for all the listed above in the meanwhile ^^
> 
> However, there's just one more thing i couldn't achieve::
> 
> > * for the daxyView (and WeekView), i'd like to show just between 8AM and 6PM... is it possible ?
> > * if not, could i programatically scroll the day view in order that 12 o'clock is in the middle of the screen ?
> > * how to ?
> 
> Edit: i did find the scrollOffset param, but how to midScroll ? just give an integer wont fit for each phone... can we somehow have access to the size of the scrollable view ?
> 
> Thanks in advance, regards.

The only way I could do that was using offset, but it is buggy if the views are out of the tree (imagine a button toggling each view style: day, week and month).

For day, that would be scrollOffset: (_currentDateTime.hour * 60.0 + _currentDateTime.minute) * 0.7 (because the default heightPerMinute is `0.7).

For week, that would be scrollOffset: (_currentDateTime.hour * 60 + _currentDateTime.minute) * 0.823 because, well, even if here heightPerMinute is 1.0, that doesn't work, so to be in pair with the first view, it must be something like 0.823.

It seems each view is made by a completely different developer =\ Almost giving up on this package.

Scroll offset (when it works) scrolls EVERY DayView page (no matter if you set scrollOffset to 0 afterwards). It's VERY annoying. WeekView doesn't scroll each page (what is expected). Nevertheless, when you hide some view, the scroll offset no longer works.

**Comment by ravilsimform** [comment]
Hi @Gobmichet
- days' labels (I'd want the french days or abreviations) For day’s label you can use

```
final List<String> weekTitles = ["Mon", "Tue", "Wed", "Thu", "Fri", "S", "S”];

weekDayBuilder: (int value) {
  return WeekDayTile(
    dayIndex: value,
    backgroundColor: value > 4 ? Colors.red : Colors.blue,
    textStyle: TextStyle(fontSize: 10),
    weekDayStringBuilder: (value) {
      //return value.weekdayToFullStringFromInt;
      return weekTitles[value];
    },
 
  );
},
```

- For am/pm stuff you can check **_timeLineBuilder** method and customize am/pm format to 24-hour format.

https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/blob/master/example/lib/widgets/day_view_widget.dart


- Four Start dayView and weekView at 13 pm you can start using

`startHour: 13`

**Comment by PRBaraiya** [comment]
Closing this issue for now as main questions are answered. Please raise a new issue if there is other queries.
