### ISSUE TITLE
Can I set the initial time to be the actual time in day view

### ISSUE THREAD

**Issue by krekzsolti** [SimformSolutionsPvtLtd/flutter_calendar_view#221]
The initial time is now the start of the day. I would like to set the displayed day view for the actual time.

**Comment by JCKodel** [comment]
Same here.

The only way I could do that was using offset, but it is buggy if the views are out of the tree (imagine a button toggling each view style: day, week and month).

For day, that would be `scrollOffset: (_currentDateTime.hour * 60.0 + _currentDateTime.minute) * 0.7` (because the default `heightPerMinute` is `0.7).

For week, that would be `scrollOffset: (_currentDateTime.hour * 60 + _currentDateTime.minute) * 0.823` because, well, even if here `heightPerMinute` is `1.0`, that doesn't work, so to be in pair with the first view, it must be something like `0.823`.

It seems each view is made by a completely different developer =\ Almost giving up on this package.
