### ISSUE TITLE
MonthView cellBuilder - titleColor not showing correct colour

### ISSUE THREAD

**Issue by ronny-strath** [SimformSolutionsPvtLtd/flutter_calendar_view#323]
I'm trying to implement dark mode in my app, but when I set the titleColor in my custom FilledCell to Colors.White, it's not showing as fully white - is there a way to change that? 
![Capture](https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/assets/94052830/4f77e9ad-4394-4cd1-94fe-381f8efe6818)

This is my code:
```
cellBuilder: (date, events, isToday, isInMonth) => FilledCell(
                date: date,
                events: events,
                shouldHighlight: isToday,
                titleColor:
                    isInMonth ? Colors.white : Color.fromRGBO(0, 0, 43, 10),
                backgroundColor:
                    isInMonth ? Color.fromRGBO(0, 0, 43, 10) : Colors.grey,
              )
```

Thanks!

**Comment by ParthBaraiya** [comment]
@ronny-strath You don't have to add the condition for `titleColor`. In `FilledCell` there is a condition where, if `isInMonth` is true, it will display the color same as `titleColor` else, it will show the `titleColor` with 40% opacity.

If you need other changes, you can create your own widget and use it instead of `FilledCell`.

I'm closing this issue for now. Please create another issue if required.
