### ISSUE TITLE
Bug Week View.  Today 10pm to tommorw 8am event will trhow an error

### ISSUE THREAD

**Issue by edoliantesjr** [SimformSolutionsPvtLtd/flutter_calendar_view#96]
`_calendarWeekEventList.add(CalendarEventData(
              date: DateTime(2022, 08, 14, 20, 0),
              startTime: DateTime(2022, 08, 14, 20, 0),
              endTime: DateTime(2022, 08, 15, 8, 23),
              endDate: DateTime(2022, 08, 15, 8, 23),
              title: '${DateFormat.jm().format(_startDate)} '
                  '- ${DateFormat.jm().format(_endDate)} '
                  '\n${_provider.name}',
              event: _event.toJson(),
              description: _event.$id,
              color: colorFromString(_provider.color),
            ));`

Error Message:
startDate must be less than endDate.
This error occurs when you does not provide startDate or endDate in CalendarEventDate or provided endDate occurs before startDate.
'package:calendar_view/src/event_arrangers/side_event_arranger.dart':
Failed assertion: line 130 pos 11: '!(endTime.getTotalMinutes <= startTime.getTotalMinutes)'

**Comment by ParthBaraiya** [comment]
Hello @edoliantesjr That is the expected behaviour as we do not have the support for multi-day events yet.

 Current implementation ignores dates in startTime and endTime parameters. So, If you have Date with value `DateTime(2022, 08, 14, 14, 20)` only `hours` and `minutes` will be considered. Year, Month and Day will be ignored.

We are planning to implement this in near future.

**Comment by ParthBaraiya** [comment]
I'm closing this issue for now as we already have similar issue #23 open.

**Comment by Muhammed-Ayad** [comment]
Is the problem solved?
